version: '3.8'
services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    networks:
      - default
    restart: unless-stopped
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
      # - type: bind
      # source: ./nginx/index.html
      # target: /usr/share/nginx/html/index.html
      # - type: bind
      #   source: ./nginx/favicon.ico
      #   target: /usr/share/nginx/html/favicon.ico
      - type: bind
        source: ./nginx/dist
        target: /usr/share/nginx/html
      # - type: bind
      #   source: ./nginx/.htpasswd
      #   target: /etc/nginx/.htpasswd
      # - type: bind
      #   source: /etc/letsencrypt/live/secures-developer-web.tk/fullchain.pem
      #   target: /etc/letsencrypt/live/secures-developer-web.tk/fullchain.pem
      # - type: bind
      #   source: /etc/letsencrypt/live/secures-developer-web.tk/privkey.pem
      #   target: /etc/letsencrypt/live/secures-developer-web.tk/privkey.pem
    depends_on:
      - api_server
  api_server:
    build:
      context: .
    container_name: api_server
    networks:
      - default
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /opt/app/src
      - type: bind
        source: ./@types
        target: /opt/app/@types
      - type: bind
        source: ./tsconfig.json
        target: /opt/app/tsconfig.json
      - type: bind
        source: ./package.json
        target: /opt/app/package.json
      - type: bind
        source: ./yarn.lock
        target: /opt/app/yarn.lock
      - type: bind
        source: ./shell/init
        target: /opt/app/shell/init
networks:
  default:
    name: 'div-web-network'
